### PR TITLE
Https proxy and proxy auth

### PR DESCRIPTION
**Pull request by the-red**
I use https proxy server and proxy authentication.
`Connection#setProxy()` is not support https and proxy-auth.
How about add `Connection#setHttpsProxy()` function, 
and add `proxyUsername` `proxyPassword` parameters?

### CODE REVIEW

**Comment by the-red** [comment]
I think this documentation is wrong.
https://kintone.github.io/kintone-js-sdk/latest/reference/connection/#setproxyproxyhost-proxyport

```
Set the proxy for the axios option
```

For `setProxy()` function, not "for the axios" but "for the [tunnel](https://www.npmjs.com/package/tunnel)". Isn't it?

**Comment by trinhhunganh** [comment]
> I use https proxy server

Can you please elaborate more on this matter? Do you mean that your proxy server supports https traffic forwarding? Or do you mean that to connect to your proxy server, a client must use https?
Example
proxy which supports HTTPS traffic: http://some-proxy.xyz:3128
SSL secured proxy: https://secured-proxy.xyz:443

Which of the above is your kind of proxy?
Please, help me make this clear.
Thank you!

**Comment by the-red** [comment]
I mean this!
```
SSL secured proxy: https://secured-proxy.xyz:443
```

**Comment by trinhhunganh** [comment]
> I mean this!
> 
> ```
> SSL secured proxy: https://secured-proxy.xyz:443
> ```

I see, well in this case tunnel.httpsOverHttps is needed indeed.
Thank you for your confirmation!

**Comment by trinhhunganh** [comment]
@Red
I have merged our main development branch to yours and modified some code to add support for including certificate.
I will now merge your pull request to the main development branch.
Thank you for your contribution!

**Pull request merged**
